In [ ]:
import numpy as np

def create_array(dim1,dim2,dim3,ini_val):
  array = np.full((dim1, dim2, dim3), ini_val)
  return array

dim1 = 3
dim2 = 4
dim3 = 5
ini_val = 2
result_array = create_array(dim1, dim2, dim3, ini_val)

print('3D array:')
print(result_array)

3D array:
[[[2 2 2 2 2]
  [2 2 2 2 2]
  [2 2 2 2 2]
  [2 2 2 2 2]]

 [[2 2 2 2 2]
  [2 2 2 2 2]
  [2 2 2 2 2]
  [2 2 2 2 2]]

 [[2 2 2 2 2]
  [2 2 2 2 2]
  [2 2 2 2 2]
  [2 2 2 2 2]]]
